package com.jarimport.dl.dayhabit.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jarimport.dl.dayhabit.entity.Habit;

import com.jarimport.dl.dayhabit.entity.HabitDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig habitDaoConfig;

    private final HabitDao habitDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        habitDaoConfig = daoConfigMap.get(HabitDao.class).clone();
        habitDaoConfig.initIdentityScope(type);

        habitDao = new HabitDao(habitDaoConfig, this);

        registerDao(Habit.class, habitDao);
    }
    
    public void clear() {
        habitDaoConfig.clearIdentityScope();
    }

    public HabitDao getHabitDao() {
        return habitDao;
    }

}
